config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post 'transform', to: 'home#transform'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def transform
    if (transformer_params[:file] && transformer_params[:file].path.split('.').last == 'csv')
      @transformer = CsvTransformService.new(
        transformer_params[:file].path,
        transformer_params[:date],
        transformer_params[:removal_date]
      )
      @result = @transformer.result
      send_data @result.read, filename: 'result.zip'
    else
      redirect_to root_path, alert: 'Error! Please try again.'
    end
  end

  private

  def transformer_params
    @transformer_params ||= params.require(:transformer).permit(:file, :date, :removal_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_style(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/home/_form.html.slim
= simple_form_for :transformer, url: transform_path, method: :post, html: { class: 'with-parsley' } do |f|
  .row
    .col-xs-12.col-md-3
      = f.input :file, as: :file, required: true, input_html: { class: 'form-control', data: { 'parsley-extension' => 'csv', disable_with: false } }
    .col-xs-12.col-md-3
      = f.input :date, required: true, input_html: { class: 'date-picker form-control' }
    .col-xs-12.col-md-3
      = f.input :removal_date, required: true, input_html: { class: 'date-picker form-control' }
    .col-xs-12.col-md-3
      = f.submit 'Export CSV', class: 'btn btn-default'

app/views/home/index.html.slim
#home-index-container
  = render 'form'
  #file-detail.hide
  table#file-content-preview.table.table-striped.nowrap.data-table.hide

app/views/layouts/application.html.slim
doctype html
html
  head
    title CSV Transformer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body class="#{params[:controller].gsub('/', ' ')} #{params[:action]}"
    = render 'shared/header'
    = render 'shared/flash'
    .main-content
      = yield
    = render 'shared/footer'

app/views/shared/_flash.html.slim
- flash.each do |name, msg|
  .alert.fade.in class="alert #{alert_style(name)} alert-dismissible"
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" &times;
    = msg

app/views/shared/_footer.html.slim
footer.footer
  .container
    p.text-muted &copy; 2017 Afilab, All rights reserved.

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-brand
      = link_to image_tag('logo.png'), root_path
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li= link_to "Home", root_path
        li= link_to "Your Account", edit_user_registration_path
        li= link_to "Logout", destroy_user_session_path, method: :delete
      - else
        li= link_to "Login", new_user_session_path
        li= link_to "Sign Up", new_user_registration_path